#!/usr/bin/env bash
# run-aptmerge-sandbox.sh — two-branch contradiction exercise for the
# /apt-merge doctrine (T3-apt-merge-skill §4.2, M3-clean-gate §8 Q3).
# Drives the skill's recipe by hand in a throwaway repo: divergence, the
# designed events.jsonl conflict, the prefix+append resolution, the gate
# catching the cross-branch contradiction, append-only repair via
# entity.reopened + decision, and the ff landing on main. Also asserts the
# §6 Q1 resolution: clean merges bypass the hooks and need no seal.
# Exits 0 when every case passes; 1 on the first failure.
set -uo pipefail
cd "$(dirname "$0")" || exit 2
WT_ROOT="$(cd ../../.. && pwd)"
GATE_CHECK="$WT_ROOT/agent-plan-tracker/scripts/gate-check.sh"
INSTALL_GUARD="$WT_ROOT/agent-plan-tracker/scripts/install-hook.sh"
FAIL=0

check() { # check <desc> <test-expr...>
  local desc="$1"; shift
  if "$@"; then
    echo "  ok: $desc"
  else
    echo "  FAIL: $desc"
    FAIL=1
  fi
}

check_absent() { # check_absent <desc> <grep-pattern> — pattern must NOT match $OUT
  local desc="$1" pattern="$2"
  if grep -q "$pattern" <<<"$OUT"; then
    echo "  FAIL: $desc"
    FAIL=1
  else
    echo "  ok: $desc"
  fi
}

run() { # run <cmd...> -> sets OUT, CODE
  OUT="$("$@" 2>&1)"
  CODE=$?
}

# --- sandbox setup --------------------------------------------------------
SANDBOX="$(mktemp -d /tmp/apt-merge-sandbox.XXXXXX)" || exit 2
trap 'rm -rf "$SANDBOX"' EXIT
unset APT_DATA_DIR  # a leaked override would point the sandbox at real data

git init -q -b main "$SANDBOX/work"
cd "$SANDBOX/work" || exit 2
git config user.email sandbox@example.invalid
git config user.name "apt sandbox"
mkdir -p .agent-plan-tracker
bash "$INSTALL_GUARD" >/dev/null  # the capture guard is part of the doctrine
# Derived artefacts are regenerated by every gate run (lazy cache rebuild);
# tracking them would make branch switches dirty. The log alone is the record.
printf '.agent-plan-tracker/cache.sqlite\n.agent-plan-tracker/projection.json\n.agent-plan-tracker/summary.md\n.agent-plan-tracker/.last-capture\n' > .gitignore

append_ev() { # append_ev <id4> <type> <entity_id> <summary>
  printf '{"event_id": "dddd%s-0000-4000-8000-00000000%s", "type": "%s", "actor": "al", "confidence": "explicit", "schema_version": "0.3.0", "entity_type": "plan", "entity_id": "%s", "attributes": {"summary": "%s"}}\n' \
    "$1" "$1" "$2" "$3" "$4" >> .agent-plan-tracker/events.jsonl
}
append_seal() { # append_seal <id4> <message_first_line>
  printf '{"event_id": "dddd%s-0000-4000-8000-00000000%s", "type": "commit.recorded", "actor": "al", "confidence": "explicit", "schema_version": "0.3.0", "attributes": {"message_first_line": "%s", "author": "al", "date": "2026-06-10"}}\n' \
    "$1" "$1" "$2" >> .agent-plan-tracker/events.jsonl
}
append_decision() { # append_decision <id4> <ref-id4> <text>
  printf '{"event_id": "dddd%s-0000-4000-8000-00000000%s", "type": "decision", "actor": "al", "confidence": "explicit", "schema_version": "0.3.0", "attributes": {"text": "%s", "event_ids": ["dddd%s-0000-4000-8000-00000000%s"]}}\n' \
    "$1" "$1" "$3" "$2" "$2" >> .agent-plan-tracker/events.jsonl
}
stamp() { date +%s > .agent-plan-tracker/.last-capture; }

# Adoption: SBX-X created, accepted, sealed — main's baseline.
append_ev   0001 entity.created  SBX-X "sandbox plan X, born draft"
append_ev   0002 entity.accepted SBX-X "operator acceptance"
append_seal 0003 "sandbox: adopt tracker"
git add -A && stamp && git commit -qm "sandbox: adopt tracker"

# --- Case 1: main unmoved -> fast-forward is the whole integration --------
echo "== lightest integration: ff when main is unmoved"
git checkout -qb feat-ff
append_ev   0004 entity.extended SBX-X "branch work, main unmoved"
append_seal 0005 "sandbox: ff step"
git add -A && stamp && git commit -qm "sandbox: ff step"
git checkout -q main
run git merge --ff-only feat-ff
check "ff merge exits 0"                [ "$CODE" -eq 0 ]
check "no merge commit created"         [ "$(git rev-list --parents -n1 HEAD | wc -w)" -eq 2 ]
run bash "$GATE_CHECK" --repo-root "$PWD"
check "gate green after ff"             [ "$CODE" -eq 0 ]

# --- Case 2: both logs grew -> conflict, contradiction, repair, land ------
echo "== divergence: branch progresses SBX-X while main completes it"
git checkout -qb feat-b
append_ev   0006 entity.progressed SBX-X "progressed on the branch, concurrently"
append_seal 0007 "sandbox: progress X on branch"
git add -A && stamp && git commit -qm "sandbox: progress X on branch"
git checkout -q main
append_ev   0008 entity.completed SBX-X "completed on main, concurrently"
append_seal 0009 "sandbox: complete X on main"
git add -A && stamp && git commit -qm "sandbox: complete X on main"

echo "== the designed trigger: events.jsonl conflicts, never suppressed"
git checkout -q feat-b
run git merge main
check "merge stops on conflict"         [ "$CODE" -ne 0 ]
check "events.jsonl is the conflict"    bash -c 'git status --porcelain | grep -q "^UU .agent-plan-tracker/events.jsonl"'

echo "== the recipe: main's log is the prefix, branch blocks append after"
BASE="$(git merge-base HEAD MERGE_HEAD)"
PREFIX=$(($(git show "$BASE:.agent-plan-tracker/events.jsonl" | wc -l)))
{ git show "MERGE_HEAD:.agent-plan-tracker/events.jsonl"
  git show "HEAD:.agent-plan-tracker/events.jsonl" | tail -n +"$((PREFIX + 1))"
} > .agent-plan-tracker/events.jsonl
git add .agent-plan-tracker/events.jsonl
check "main's log is a strict prefix"   bash -c 'git show "MERGE_HEAD:.agent-plan-tracker/events.jsonl" | cmp -s - <(head -n "$(git show "MERGE_HEAD:.agent-plan-tracker/events.jsonl" | wc -l | tr -d " ")" .agent-plan-tracker/events.jsonl)'

echo "== the guard fires on a conflicted merge: reconciliation is capturable"
# The sandbox runs sub-second, so the resolved file and the last stamp share
# a timestamp; production has real time between capture and the next edit.
# Backdate the stamp to make the staleness observable.
echo 1000000000 > .agent-plan-tracker/.last-capture
run git commit -m "sandbox: merge main into feat-b"
check "commit refused before capture"   [ "$CODE" -ne 0 ]
check "guard names the missing capture" grep -qi "capture" <<<"$OUT"

append_seal 000a "sandbox: merge main into feat-b"
git add .agent-plan-tracker/events.jsonl && stamp
run git commit -m "sandbox: merge main into feat-b"
check "sealed merge commit concludes"   [ "$CODE" -eq 0 ]

echo "== gate backstop: the merged contradiction blocks until ruled on"
run bash "$GATE_CHECK" --repo-root "$PWD"
check "exit 1"                          [ "$CODE" -eq 1 ]
check "resurrection names SBX-X"        grep -q '^BLOCK \[resurrection-without-reopen\].*SBX-X' <<<"$OUT"
check_absent "no orphaned seals"        '^BLOCK \[seal-commit\]'

echo "== append-only repair: the operator's ruling reopens X"
append_ev       000b entity.reopened SBX-X "operator ruling: branch work was real and continues; X reopens"
append_decision 000c 000b "Cross-branch contradiction surfaced by /apt-merge: main completed X while the branch progressed it. Ruling: the branch work stands, X reopens."
append_seal     000d "sandbox: reconcile X after merge"
git add -A && stamp && git commit -qm "sandbox: reconcile X after merge"
run bash "$GATE_CHECK" --repo-root "$PWD"
check "gate green after the ruling"     [ "$CODE" -eq 0 ]
check "PASS verdict"                    grep -q '^gate-check: PASS' <<<"$OUT"

echo "== land: main fast-forwards to the reconciled, gated state"
run git checkout main
check "checkout main succeeds"          [ "$CODE" -eq 0 ]
run git merge --ff-only feat-b
check "ff landing exits 0"              [ "$CODE" -eq 0 ]
check "main is at the branch tip"       [ "$(git rev-parse HEAD)" = "$(git rev-parse feat-b)" ]
run bash "$GATE_CHECK" --repo-root "$PWD"
check "gate green on main"              [ "$CODE" -eq 0 ]

# --- Case 3: clean merge bypasses the hooks, needs no seal (§6 Q1) --------
echo "== clean merge: no conflict, no capture, sealless merge commit tolerated"
git checkout -qb feat-c
echo "branch side" > BRANCH.md
git add BRANCH.md && git commit -q --no-verify -m "sandbox: readme on branch"
git checkout -q main
echo "main side" > MAIN.md
git add MAIN.md && git commit -q --no-verify -m "sandbox: readme on main"
run git merge --no-edit feat-c
check "clean merge exits 0 (no hook)"   [ "$CODE" -eq 0 ]
check "a merge commit exists"           [ "$(git rev-list --parents -n1 HEAD | wc -w)" -eq 3 ]
run bash "$GATE_CHECK" --repo-root "$PWD"
check "gate green, sealless merge ok"   [ "$CODE" -eq 0 ]
check_absent "no BLOCK lines"           '^BLOCK'

echo
if [ "$FAIL" -eq 0 ]; then
  echo "apt-merge sandbox: ALL PASS"
else
  echo "apt-merge sandbox: FAILURES (see above)"
fi
exit "$FAIL"
